drop table developer;
CREATE TABLE IF NOT EXISTS developer (
  id             INT PRIMARY KEY AUTO_INCREMENT,
  DEVELOPER_NAME VARCHAR(255) NOT NULL,
  ACCOUNT_NAME   VARCHAR(255) NOT NULL,
  SKILL_NAME     VARCHAR(255) NOT NULL
);
